### ISSUE TITLE
[SIM] Duplicate package name

### ISSUE THREAD

**Issue by horverno** [jkk-research/sim_wayp_plan_tools#4]
After `colcon build --symlink-install --packages-select gamma_bringup` the following error shows up:

```powershell
ERROR: colcon:colcon build: Duplicate package names not supported:
- gamma_bringup:
  - src/jkk_utils/gamma_bringup
  - src/sim_wayp_plan_tools/gamma_bringup
  ````
  
  Possible solution is to rename `gamma_bringup` >> `gamma_bringup_sim`
  
  ```
  colcon build --symlink-install --packages-select gamma_description gamma_gazebo gamma_bringup_sim
  ```

**Comment by rudolfkrecht** [comment]
Packages have been renamed as gammasim_bringup, gammasim_description, and gammasim_gazebo.
