### ISSUE TITLE
Cannot echo topic '/gamma/velocity', as it contains more than one type: [std_msgs/msg/Float32, std_msgs/msg/Float64]

### ISSUE THREAD

**Issue by umiklos** [jkk-research/sim_wayp_plan_tools#6]
Cannot echo topic '/gamma/velocity', as it contains more than one type: [std_msgs/msg/Float32, std_msgs/msg/Float64]

**Comment by rudolfkrecht** [comment]
I could not replicate the issue, I can echo '/gamma/velocity', ros2 topic type returns 'std_msgs/msg/Float64.

**Comment by rudolfkrecht** [comment]
The described issue was caused by an outside factor, not by the simulator.
